version: '2'

volumes:
  spotifycache:

services:

  # Core services
  # -- Required for a fully featured installation of balenaSound
  # -- Mutiroom services can be removed if not using multiroom mode
  audio:
    build:
      context: ./core/audio
      dockerfile: ./Dockerfile.template
    privileged: true
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    ports:
      - 4317:4317

  sound-supervisor:
    build: 
      context: .
      dockerfile: ./core/sound-supervisor/Dockerfile.template
    network_mode: host
    labels:
      io.balena.features.balena-api: '1'
      io.balena.features.supervisor-api: 1

  multiroom-server:
    build:
      context: ./core/multiroom/server
      dockerfile: ./Dockerfile.template
    restart: on-failure
    ports:
      - 1704:1704
      - 1705:1705
      - 1780:1780

  multiroom-client:
    build: 
      context: ./core/multiroom/client
      dockerfile: ./Dockerfile.template
    restart: on-failure

  logging:
    image: balenablocks/log2screen
    privileged: true
    restart: always
    network_mode: host
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1

  # Plugins
  # -- Additional plugins can be added. See https://sound.balenalabs.io/docs/plugins.
  # -- Remove unwanted plugins as needed
  bluetooth:
    build:
      context: ./plugins/bluetooth
      dockerfile: ./Dockerfile.template
    restart: on-failure
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: 1

  airplay:
    build:
      context: ./plugins/airplay
      dockerfile: ./Dockerfile.template
    restart: on-failure
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: 1

#  spotify:
#    build:
#      context: ./plugins/spotify
#      dockerfile: ./Dockerfile.template
#    restart: on-failure
#    privileged: true
#    network_mode: host
#    volumes:
#      - spotifycache:/var/cache/raspotify
